### ISSUE TITLE
Keyboard focus is in two places when menu is open

### ISSUE THREAD

**Issue by JimH44** [franc6/Ketarin#32]
In the Linux version (1.0, based on mainline 1.8.10.1):
When I do Alt-F to open the File menu and then tap the down arrow key to step through the items in the File menu, the highlight also moves through the list of recipes.
When I tap Enter to open the selected File Menu item (eg. Settings), the currently-selected recipe opens for editing.
This should not happen, the keyboard focus should only be in the menu.
The Windows version behaves properly.

**Comment by franc6** [comment]
As nearly as I can determine, this is a bug in Mono.  The problem also occurs with the context menu, which makes it impossible to use the context menu from the keyboard, since the selection changes when you change which context menu item you want to invoke! :)

I've found a way to modify the code to get around this, but I'm checking with floele, to see how he wants to handle it -- it's a lot of minor code changes to fix it, if he wants to keep the code how it is for Windows, it'll be especially problematic.

**Comment by JimH44** [comment]
Well, we can survive having to use the mouse instead of the keyboard. 
It's just a bit tricky controlling the mouse from the other side of the 
world sometimes, if the internet is slow!

It would be better to leave this problem there, I think, than have lots 
of differences between the Windows and Linux versions.

Jim

**Comment by franc6** [comment]
Word from floele is no to MenuStrip.  And after taking a quick look at MenuStrip on Windows, I gotta agree.  It's just plain ugly.  And maintaining separate code would be painful as noted above.  I'm going to close this one as "won't fix".  It's unfortunate that MenuStrip on Mono is what MenuItem is on Windows and the other way around.  :(

I'll try to work up a small sample app that shows the problem, and submit a bug to the Mono folks, if I can't find one already.  Maybe they'll fix it, perhaps by replacing the implementation of MenuItem with the MenuStrip implementation.  Or maybe reverse the two implementations. :)
