### ISSUE TITLE
PageUp key goes by lines

### ISSUE THREAD

**Issue by JimH44** [franc6/Ketarin#34]
When I have selected one of the recipes, I can type the first letter of some other part of the alphabet, and Ketarin for Linux jumps nicely to a recipe that begins with that letter.

Then, when I want to step quickly through similar recipes and tap the PageUp key, the highlight moves up just one line, not a screenful as I expect. (This happens when the highlight is at the top of the screen.)

Similarly, PageDown takes me to the last row in the window, and then goes down row-by-row, instead of page by page.

I'm using Windows Remote Desktop at my end, and on the server, running xrdp.

**Comment by franc6** [comment]
I’ll double-check, but that sounds like a Mono bug. But it might be in ObjectListViewer — there’s a lot of Windows-specific code in there, and I may well have missed that it had custom code to handle page up/down. :(

TOM

-- 
Preserve wildlife -- pickle a squirrel!

**Comment by franc6** [comment]
I can't reproduce the problem with page down, only page up.  It doesn't seem to matter where I start, either.  Additionally, for the first two presses, page up works as expected (i.e. it selects the first item in the view on the first keypress, and goes up one page on the second keypress; the third and subsequent keypresses consistently move up just one row).

There's no code to handle page up/down in the ObjectListViewer code, so this is definitely a Mono bug -- or perhaps a GTK# bug?

FYI: I'm using the MS Remote Desktop app on macOS, version 8.0.41 (newer versions don't work well with xrdp, in my experience).  Using a VNC client to view the console (it's a VM on XenServer), I see the same behaviors.

**Comment by franc6** [comment]
Note to self: I still see this bug on March 29, 2021.  I'm still pretty sure the problem is in Mono or a lower level.  Attempting to fix this inside ObjectListView doesn't work well, largely because the TopItem property isn't updated properly after a sort.  Likewise, after a sort, Index for each item may or may not be updated, and selecting items manually sometimes resorts in the wrong index being stored.  Worse, the calculation of the window size isn't always correct, so even if items are not re-sorted, paging up won't always go up by a full page or can go up more than a page.

**Comment by JimH44** [comment]
No worries.

Would you like to list this problem in the .md file of differences 
between the Linux version and the Windows version and close the issue?

Jim

**Comment by franc6** [comment]
There was already a note in Linux-behavior.md, but I've updated it a little bit.
