### ISSUE TITLE
Click in Page Down area of scrollbar has different effect

### ISSUE THREAD

**Issue by JimH44** [franc6/Ketarin#35]

**Comment by JimH44** [comment]
In Ketarin for Windows, when the scrollbar slider is near the top of the vertical scroll bar, and there is a large area in the Page Down area, I can move the pointer half-way down the Page Down area and click several times. For each click, the list of recipes scrolls by one page, and eventually the slider moves under my pointer.

In the Linux version, when I do that, the list of recipes scrolls one page and then immediately all the way until the slider is under the pointer.

Some research shows that this behaviour is called “gtk-primary-button-warps-slider”, and it seems it came into Linux in gtk version 3. I found out about it at
[stack exchange](https://unix.stackexchange.com/questions/276005/scrollbar-moves-to-where-i-click), and here are the details from the [gnome developer site](https://developer.gnome.org/gtk3/stable/GtkSettings.html#GtkSettings--gtk-primary-button-warps-slider).

I set the value to false in ~/.config/gtk-3.0/settings.ini, logged out and in again, but that didn't change the behaviour of Ketarin.

Since this is a Windows program ported to Linux, it would be helpful if it had the same behaviour on both platforms. In Windows (at least in Ketarin and FireFox), a single click scrolls a page, and a Shift-click warps the slider to where the click happened.

I think I would like Ketarin on Linux to continue to ignore the setting of the property
“gtk-primary-button-warps-slider”.

**Comment by JimH44** [comment]
Also, we should have something about this in the documentation for the Linux version.

**Comment by franc6** [comment]
The information you were reading is incorrect on Ubuntu systems, and I'm not convinced it's correct for GTK in general, even.  Changing that setting doesn't affect anything as far as I have been able to determine in the past or now.  Open up any other program with a scrollbar, and you'll see it also behaves the same way.  GTK scrollbars work the way GTK developers want them to work, which is in a manner contrary to how scrollbars work in everything else. :(  Short of attempting to implement my own scrollbars, there's nothing we can do about this.  And I haven't written my own scrollbars since the 90s -- I'm not sure how to do it for a project like this.
