### ISSUE TITLE
In Find box, echo is very slow

### ISSUE THREAD

**Issue by JimH44** [franc6/Ketarin#37]
When I type Ctrl-F to open the Find input text box and type text in there, the echoing is so slow that I first thought I had to type the whole word and tap Enter to see it.  
That is not the case. The individual characters do appear, but after a long delay.

The attached screenshot shows the result of searching for "android" (where I put the red arrows). Then I started backspacing over the text in the Find box. The cursor moved left quickly, but the rubbing out was very slow, to the effect that I had time to take a screenshot before the erasing happened.
![Ctrl-F to Find echo very slow - backspacing](https://user-images.githubusercontent.com/8330030/55405310-80c6fc80-55a5-11e9-8714-bdca92017096.jpg)

The Windows version is also quite slow in this Find box.
Not a show-stopper, but if it can't be improved easily, I think we should make a note about it.

**Comment by franc6** [comment]
The problem is in how it does the search; characters are echoed only after the search (on a per-change basis, be it adding or deleting a character), not immediately.  If search were significantly faster, you wouldn't see any problems here.  I'm not sure if the biggest issue is in Mono or in the Ketarin code.  Any fix is likely to be in the ObjectListView control, or possibly in ApplicationJobsListView.

**Comment by franc6** [comment]
Problem is with ObjectListView and how search works.  Search will remove all jobs and add only what matches to the ObjectListView.  So when typing the first few letters (which will likely match all or nearly all  jobs), it takes a very long time because ObjectListView is so slow.
It'd be better if ObjectListView had its own filtering concept, but that would make its code significantly more complex.  Speeding up adding and removing objects from ObjectListView isn't practical under Mono at this time -- largely because it'll crash. :)

**Comment by JimH44** [comment]
So that could be another warning in the file of differences -- Search 
doesn't work fast enough on Linux.

Or would you like to remove the Search option and note that in the 
differences file and close the issue?

Jim

**Comment by franc6** [comment]
I've added a note to Linux-behavior.md.
