### ISSUE TITLE
Files and directories created with incorrect permissions

### ISSUE THREAD

**Issue by JimH44** [franc6/Ketarin#41]
It seems Ketarin has an effective umask of 077, as the permissions on newly downloaded files are  
- rw- --- --- (See screenshot 
![Permissions on saved files](https://user-images.githubusercontent.com/8330030/65037329-c67b5400-d990-11e9-90fd-8c3d920034fd.jpg)
)

We have been correcting the permissions with a script, to make the permissions  
\- rw- rw- r-- so that clients using rsync can download the files. (Clients have permissions as "others".) But this leaves some time between the downloading by Ketarin and the adjustment by the script.

It would be helpful if Ketarin could have an effective umask of 002, so the permissions on files that it saves to disk would be  
\- rw- rw- r-- .

(Since Ketarin was developed in the Windows environment, the original code may not pay any attention to these permissions, so this may need to be a new bit of code in the Mono branch.)

Thanks for thinking about this,  
Jim

**Comment by franc6** [comment]
The problem is deeper.  Files and directories are explicitly created with permissions only for the current user (specifically, 0600 for files, 0700 for directories).  I suspect this is because someone didn't understand umask, or assumed that umask would be set incorrectly, with permissions being unexpectedly permissive (probably because default umask allows group and world read permissions).  It's a challenging problem to solve, as defaults for Windows and Posix systems can be very different (and on Windows, possibly controlled by group policy, which the user can't change).

I think the idea is that programmers would be setting ACLs after the fact, which would work fine, if you want to do something particular, but doesn't work for default cases at all.

There's no good way to fix this, especially since Mono.Posix doesn't expose umask().  So I think a hammer is the best way to go. :(

1) Dynamically load libc
2) call umask() to find current umask
3) Mask 0666 with current umask
4) Apply new permissions with chmod().

This should be done after File.Copy() is called in DoDownload() in Updater.cs.  Note the permission set 0666.  We don't want to set execute permissions on files that are unlikely to be truly executable. :)

To be more efficient, dynamically load libc in a new class which gets instantiated at start time, and invoke a method from it (loading libc dynamically ought to be very fast, since it's already loaded, but if you're downloading thousands of files, the overhead of the function calls will be significant, so best to avoid them).

This way, umask will be properly applied.  umask can be easily set to 002 if that's what is desired.

To test what really happens, set umask to 0200.  If the full directory structure already exists, you'll see file permissions set to 0400 (note execute perms are not currently set for anything).  If you try it with a non-existent directory structure, you'll see plenty of errors (because write permissions aren't set for owner, because umask is applied during directory creation, too).

**Comment by JimH44** [comment]
Fixed indeed :-)
Mono version 1.0.25 on Lubuntu 16.04 produced permissions - rw- --- --- as in this screenshot:
![Permissions on file downloaded by Ketarin 4 Linux vn 1 0 25](https://user-images.githubusercontent.com/8330030/67179525-49754b80-f422-11e9-816f-0b26892601e3.jpg)

Mono version 1.0.27 on the same system produced - rw- rw- r-- like this:
![Permissions on file downloaded by Ketarin 4 Linux vn 1 0 27](https://user-images.githubusercontent.com/8330030/67179586-77f32680-f422-11e9-9261-bcb478f99aca.jpg)

Thanks,
Jim
