### ISSUE TITLE
Replace Open and Save As dialogs

### ISSUE THREAD

**Issue by franc6** [franc6/Ketarin#42]
This will let us fix #14 and handle some issued previously reported via email.

Current (as of build 28) problems:
1) Hitting Enter doesn't invoke the Save or Open button; you have to click the button separately (or double-click a file in the view).
2) There are no icons in the file list, and the icons on the dialog are wrong.
3) While you can type the name of a sub-directory and hit enter to browse to it, you can only go one level deep, and it doesn't work to go to a full path that's outside the directory which is being displayed.  I can't make this work as smoothly as I would like (because Mono doesn't support some stuff), but when done, it'll work, anyway. :)
4) I'd like to have the navigation bar on the left display all mounted file systems, too.
5) There's no "Up" button next to the "look in" drop list.

**Comment by JimH44** [comment]
I found a good way to walk down the path to the destination is to click the dropdown list above the file and folder names, select a folder and click it. Some screenshots of this in my next post, but first, a crash.
On one occasion, instead of clicking a folder, I used the down-arrow key and got stuck in /cdrom. Saw in the left pane "/home/XXXXXX" and clicked on it. The program couldn't find that folder, and crashed leaving the dialog open.
I had to find the PID and kill the Ketarin process. Here is the execution trace:

jim@langtran:/data/LT/Ketarin-Mono-1.0.28$ ./Ketarin.exe 
System.IO.DirectoryNotFoundException: Could not find a part of the path '/home/XXXXXX'.
  at System.IO.Enumeration.FileSystemEnumerator`1[TResult].CreateDirectoryHandle (System.String path, System.Boolean ignoreNotFound) <0xb5d172e0 + 0x000b8> in <285579f54af44a2ca048dad6be20e190>:0 
  at System.IO.Enumeration.FileSystemEnumerator`1[TResult]..ctor (System.String directory, System.IO.EnumerationOptions options) <0xb5d16ee0 + 0x00113> in <285579f54af44a2ca048dad6be20e190>:0

**Comment by franc6** [comment]
The crash was because I had accidentally left a hard-coded path in there.  I've just committed a change to fix that.  I had not intended to let you see that directory name. I've removed references to that directory from this issue.

**Comment by franc6** [comment]
Item #1 is fixed in issue #46.

**Comment by JimH44** [comment]
File->import and export dialog now working nicely. :-)
