### ISSUE TITLE
No scrollbar in KFileDialog's List view

### ISSUE THREAD

**Issue by JimH44** [franc6/Ketarin#47]

**Comment by JimH44** [comment]
When I first tried build 1.0.34 and did File->Import, the files at root appeared in the List view, but only the later ones in the alphabet appeared, and there was no scroll bar to let me scroll to the earlier ones to find the /data that I wanted.

I changed to Details view successfully, and the scroll bar appeared and there was /data to click on.

Then I changed back to List view and found the list in two columns for short names and one column for longer names as in this screenshot:
![No scrollbar in List view](https://user-images.githubusercontent.com/8330030/68251370-16b09180-0077-11ea-9f7e-7c19e56eeb00.jpg)

Is that the designed behaviour?

**Comment by franc6** [comment]
I've never seen the problem you describe initially.  If not everything is displayed, it's a bug, but that sounds like it'd be a problem with the ListView control -- I'm only setting which type of view to display.
The list view of the ListView control should be placing items in as many columns as necessary, and should be calculating the appropriate width of the column based on ALL the file names in the directory being displayed.  I've never seen a display like your screenshot before.  It's hard to say where exactly that bug would be, especially since I can't reproduce it:

![Screen Shot 2019-11-05 at 7 03 10 PM](https://user-images.githubusercontent.com/3240549/68256781-fba23b00-fffe-11e9-9767-e7969eaf3549.png)

You might check if there are updates to mono, gtk, or x11 libraries to be installed, too.  If there are, it could be a bug in one or more of those (e.g. a mis-interaction between the various layers) causing incorrect calculations, and which might even mean there's no scroll-bar.  Please note, though, that when showing the list view, that the only scrollbar should be a horizontal scrollbar, and never a vertical scroll bar.

**Comment by franc6** [comment]
After system updates, is this still a problem?

**Comment by JimH44** [comment]
No, it's good now. I'll close the issue.
