### ISSUE TITLE
Text in Status Bar overflows space

### ISSUE THREAD

**Issue by JimH44** [franc6/Ketarin#53]
In Mono version 1.0.39 on Lubuntu 18.04, the text in the Status bar overflows the space available, as in this screenshot:
![Status bar text overflow 2020-05-12 07-23-39](https://user-images.githubusercontent.com/8330030/81635642-ffeb5d00-9454-11ea-9a8c-b74a73f882b8.png)

**Comment by franc6** [comment]
This appears to be a bug in how mono & GTK interact.  After research, it's clearly not a bug inside the .NET implementation of the status bar; indeed, the status bar indicates the text is in the right spot, if placed manually, even though it still shows incorrectly.  When not placed manually, it shows the placement and size as actually displayed, which makes no sense given the status bar's implementation code.  Indeed, stepping through  that code, it appears to be attempting to place the text properly.  So I'm not sure what's going wrong.  JimH44 reported this bug is something they can live with for now.
